const countryData = {
    US: {
        country: 10,
        language: 'en',
        countryMentions: ['US','U.S', 'USA', 'United States', 'United States of America'],
        regions: [
            "Alabama", "AL",
            "Alaska", "AK",
            "Arizona", "AZ",
            "Arkansas", "AR",
            "California", "CA",
            "Colorado", "CO",
            "Connecticut", "CT",
            "Delaware", "DE",
            "Florida", "FL",
            "Georgia", "GA",
            "Hawaii", "HI",
            "Idaho", "ID",
            "Illinois", "IL",
            "Indiana", "IN",
            "Iowa", "IA",
            "Kansas", "KS",
            "Kentucky", "KY",
            "Louisiana", "LA",
            "Maine", "ME",
            "Maryland", "MD",
            "Massachusetts", "MA",
            "Michigan", "MI",
            "Minnesota", "MN",
            "Mississippi", "MS",
            "Missouri", "MO",
            "Montana", "MT",
            "Nebraska", "NE",
            "Nevada", "NV",
            "New Hampshire", "NH",
            "New Jersey", "NJ",
            "New Mexico", "NM",
            "New York", "NY",
            "North Carolina", "NC",
            "North Dakota", "ND",
            "Ohio", "OH",
            "Oklahoma", "OK",
            "Oregon", "OR",
            "Pennsylvania", "PA",
            "Rhode Island", "RI",
            "South Carolina", "SC",
            "South Dakota", "SD",
            "Tennessee", "TN",
            "Texas", "TX",
            "Utah", "UT",
            "Vermont", "VT",
            "Virginia", "VA",
            "Washington", "WA",
            "West Virginia", "WV",
            "Wisconsin", "WI",
            "Wyoming", "WY"
            // Add more regions
        ],
        cities: [
            "New York",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "Charlotte",
            "San Francisco",
            "Indianapolis",
            "Seattle",
            "Denver",
            "Washington",
            "Boston",
            "El Paso",
            "Nashville",
            "Detroit",
            "Oklahoma City",
            "Portland",
            "Las Vegas",
            "Memphis",
            "Louisville",
            "Baltimore",
            "Milwaukee",
            "Albuquerque",
            "Tucson",
            "Fresno",
            "Mesa",
            "Sacramento",
            "Atlanta",
            "Kansas City",
            "Colorado Springs",
            "Miami",
            "Raleigh",
            "Omaha",
            "Long Beach",
            "Virginia Beach",
            "Oakland",
            "Minneapolis",
            "Tulsa",
            "Arlington",
            "Tampa",
            "New Orleans",
            "Wichita",
            "Cleveland",
            "Bakersfield",
            "Aurora",
            "Anaheim",
            "Honolulu",
            "Santa Ana",
            "Riverside",
            "Corpus Christi",
            "Lexington",
            "Henderson",
            "Stockton",
            "Saint Paul",
            "Cincinnati",
            "St. Louis",
            "Pittsburgh",
            "Greensboro",
            "Lincoln",
            "Anchorage",
            "Plano",
            "Orlando",
            "Irvine",
            "Newark",
            "Toledo",
            "Durham",
            "Chula Vista",
            "Fort Wayne",
            "Wayne",
            "Jersey City",
            "St. Petersburg",
            "Laredo",
            "Madison",
            "Chandler",
            "Buffalo",
            "Lubbock",
            "Scottsdale",
            "Reno",
            "Glendale",
            "Gilbert",
            "Winston–Salem",
            "North Las Vegas",
            "Norfolk",
            "Chesapeake",
            "Garland",
            "Irving",
            "Hialeah",
            "Fremont",
            "Boise",
            "Richmond",
            "Baton Rouge",
            "Spokane",
            "Des Moines",
            "Tacoma",
            "San Bernardino",
            "Modesto",
            "Fontana",
            "Santa Clarita",
            "Birmingham",
            "Oxnard",
            "Fayetteville",
            "Moreno Valley",
            "Rochester",
            "Glendale",
            "Huntington Beach",
            "Salt Lake City",
            "Grand Rapids",
            "Amarillo",
            "Yonkers",
            "Aurora",
            "Montgomery",
            "Akron",
            "Little Rock",
            "Huntsville",
            "Augusta",
            "Port St. Lucie",
            "Grand Prairie",
            "Columbus",
            "Tallahassee",
            "Overland Park",
            "Tempe",
            "McKinney",
            "Cape Coral",
            "Shreveport",
            "Frisco",
            "Knoxville",
            "Worcester",
            "Brownsville",
            "Vancouver",
            "Fort Lauderdale",
            "Sioux Falls",
            "Ontario",
            "Chattanooga",
            "Providence",
            "Newport News",
            "Rancho Cucamonga",
            "Santa Rosa",
            "Peoria",
            "Oceanside",
            "Elk Grove",
            "Salem",
            "Pembroke Pines",
            "Eugene",
            "Garden Grove",
            "Cary",
            "Fort Collins",
            "Corona",
            "Springfield",
            "Jackson",
            "Alexandria",
            "Hayward",
            "Lancaster",
            "Lakewood",
            "Clarksville",
            "Palmdale",
            "Salinas",
            "Hollywood",
            "Pasadena",
            "Sunnyvale",
            "Macon",
            "Pomona",
            "Escondido",
            "Killeen",
            "Naperville",
            "Joliet",
            "Bellevue",
            "Rockford",
            "Savannah",
            "Paterson",
            "Torrance",
            "Bridgeport",
            "McAllen",
            "Mesquite",
            "Syracuse",
            "Midland",
            "Pasadena",
            "Murfreesboro",
            "Miramar",
            "Dayton",
            "Fullerton",
            "Olathe",
            "Orange",
            "Thornton",
            "Roseville",
            "Denton",
            "Waco",
            "Surprise",
            "Carrollton",
            "West Valley City",
            "Charleston",
            "Warren",
            "Hampton",
            "Gainesville",
            "Visalia",
            "Coral Springs",
            "Columbia",
            "Cedar Rapids",
            "Sterling Heights",
            "New Haven",
            "Stamford",
            "Concord",
            "Kent",
            "Santa Clara",
            "Elizabeth",
            "Round Rock",
            "Thousand Oaks",
            "Lafayette",
            "Athens",
            "Topeka",
            "Simi Valley",
            "Fargo",
            "Norman",
            "Columbia",
            "Abilene",
            "Wilmington",
            "Hartford",
            "Victorville",
            "Pearland",
            "Vallejo",
            "Ann Arbor",
            "Berkeley",
            "Allentown",
            "Richardson",
            "Odessa",
            "Arvada",
            "Cambridge",
            "Sugar Land",
            "Beaumont",
            "Lansing",
            "Evansville",
            "Rochester",
            "Independence",
            "Fairfield",
            "Provo",
            "Clearwater",
            "College Station",
            "West Jordan",
            "Carlsbad",
            "El Monte",
            "Murrieta",
            "Temecula",
            "Springfield",
            "Palm Bay",
            "Costa Mesa",
            "Westminster",
            "North Charleston",
            "Miami Gardens",
            "Manchester",
            "High Point",
            "Downey",
            "Clovis",
            "Pompano Beach",
            "Pueblo",
            "Elgin",
            "Lowell",
            "Antioch",
            "West Palm Beach",
            "Peoria",
            "Everett",
            "Wichita Falls",
            "Green Bay",
            "Daly City",
            "Burbank",
            "Richardson",
            "Pompano Beach",
            "North Miami",
            "Gresham",
            "Inglewood",
            "Waterbury",
            "League City",
            "Santa Maria",
            "Tyler",
            "Davie",
            "Lakewood",
            "Daly City",
            "Allen",
            "West Covina",
            "Sparks",
            "Wichita Falls",
            "El Cajon",
            "Rialto",
            "Las Cruces",
            "San Mateo",
            "Lewisville",
            "South Bend",
            "Lakeland",
            "Erie",
            "Brockton",
            "Sugar Land",
            "Yakima",
            "Renton",
            "Appleton",
            "Kennewick",
            "Coral Springs",
            "Norwalk",
            "South Gate",
            "Sandy Springs",
            "Jurupa Valley",
            "Hillsboro",
            "Green Bay",
            "Santa Barbara",
            "Portsmouth",
            "Odessa",
            "Lewisville",
            "Carmel",
            "Westminster",
            "Wilmington",
            "Visalia",
            "Haverhill",
            "Greeley",
            "Inglewood",
            "League City",
            "Vallejo",
            "Concord",
            "Pompano Beach",
            "Manchester",
            "Murfreesboro",
            "Lewisville",
            "Olathe",
            "Clinton",
            "Santa Maria",
            "Clovis",
            "Jacksonville",
            "Murrieta",
            "Victorville",
            "Santa Clarita",
            "Rochester",
            "West Valley City",
            "Denton",
            "Killeen",
            "McKinney",
            "Midland",
            "Victorville",
            "Billings",
            "Boulder",
            "Miami Beach",
            "Mission Viejo",
            "Meridian",
            "Lafayette",
            "Eugene",
            "Greenville",
            "Wilmington",
            "Norman",
            "Lakeland",
            "Arlington Heights",
            "Green Bay",
            "Pasadena",
            "Jackson",
            "Carlsbad",
            "Santa Clara",
            "Springfield",
            "Fairfield",
            "West Jordan",
            "Clearwater",
            "West Palm Beach",
            "Daly City",
            "Springfield",
            "Murfreesboro",
            "Santa Clara",
            "Carrollton",
            "Norman",
            "Lewisville",
            "Carlsbad",
            "Columbia",
            "Billings",
            "Lakewood",
            "Cary",
            "Westminster",
            "Beaumont",
            "Manchester",
            "College Station",
            "Richardson",
            "Santa Clara",
            "Ann Arbor",
            "Topeka",
            "Concord",
            "Lafayette",
            "Hartford",
            "Norman",
            "Sterling Heights",
            "Fairfield",
            "Cary",
            "West Jordan",
            "Lakeland",
            "Palm Bay",
            "Downey",
            "Waterbury",
            "West Covina",
            "Springfield",
            "Manchester",
            "Clinton",
            "Santa Clara",
            // Add more cities
        ]
    },
    UK: {
        country: 10,
        language: 'en',
        countryMentions: ['UK', 'United Kingdom', 'England', 'Great Britain', 'GB'],
        regions: [
            "East Midlands", "Derbyshire", "Leicestershire", "Lincolnshire", "Northamptonshire", "Nottinghamshire", "Rutland",
            "East of England", "Bedfordshire", "Cambridgeshire", "Essex", "Hertfordshire", "Norfolk", "Suffolk",
            "London", "Greater London",
            "North East", "County Durham", "Northumberland", "Tyne and Wear",
            "North West", "Cheshire", "Cumbria", "Greater Manchester", "Lancashire", "Merseyside",
            "Northern Ireland", "Antrim", "Armagh", "Down", "Fermanagh", "Londonderry", "Tyrone",
            "Scotland", "Aberdeen", "Angus", "Argyll and Bute", "Ayrshire", "Banffshire", "Berwickshire", "Caithness", "Clackmannanshire", "Dumfries and Galloway", "Dunbartonshire", "East Lothian", "Edinburgh", "Fife", "Glasgow", "Inverness", "Lanarkshire", "Midlothian", "Moray", "Orkney", "Perth and Kinross", "Renfrewshire", "Ross and Cromarty", "Roxburghshire", "Selkirkshire", "Shetland", "Stirlingshire", "Sutherland", "West Lothian", "Western Isles", "Wigtownshire",
            "South East", "Berkshire", "Buckinghamshire", "East Sussex", "Hampshire", "Kent", "Oxfordshire", "Surrey", "West Sussex",
            "South West", "Bristol", "Cornwall", "Devon", "Dorset", "Gloucestershire", "Somerset", "Wiltshire",
            "Wales", "Anglesey", "Brecknockshire", "Caernarfonshire", "Cardiganshire", "Carmarthenshire", "Clwyd", "Denbighshire", "Dyfed", "Flintshire", "Glamorgan", "Gwent", "Gwynedd", "Merionethshire", "Monmouthshire", "Montgomeryshire", "Pembrokeshire", "Powys", "Radnorshire",
            "West Midlands", "Herefordshire", "Shropshire", "Staffordshire", "Warwickshire", "West Midlands", "Worcestershire",
            "Yorkshire and the Humber", "East Riding of Yorkshire", "North Yorkshire", "South Yorkshire", "West Yorkshire"        
            // Add more regions
        ],
        cities: [
            "London",
            "Birmingham",
            "Manchester",
            "Glasgow",
            "Liverpool",
            "Edinburgh",
            "Leeds",
            "Bristol",
            "Sheffield",
            "Newcastle",
            "Leicester",
            "Belfast",
            "Nottingham",
            "Cardiff",
            "Hull",
            "Stoke-on-Trent",
            "Coventry",
            "Reading",
            "Southampton",
            "Derby",
            "Plymouth",
            "Luton",
            "Wolverhampton",
            "Sunderland",
            "Norwich",
            "Swansea",
            "Bradford",
            "Aberdeen",
            "Dundee",
            "Milton Keynes",
            "Walsall",
            "Northampton",
            "Portsmouth",
            "York",
            "Peterborough",
            "Oxford",
            "Cambridge",
            "Doncaster",
            "Ipswich",
            "Blackpool",
            "Middlesbrough",
            "Bolton",
            "Telford",
            "West Bromwich",
            "Brighton",
            "Hove",
            "Bournemouth",
            "Swindon",
            "Basildon",
            "Watford",
            "Chelmsford",
            "Slough",
            "Hastings",
            "Bedford",
            "Derry",
            "Gloucester",
            "St Albans",
            "Rotherham",
            "Southend-on-Sea",
            "Stockport",
            "Woking",
            "Eastbourne",
            "Worthing",
            "Colchester",
            "Crawley",
            "Gillingham",
            "Worcester",
            "Basingstoke",
            "Solihull",
            "Rochdale",
            "Harrow",
            "Gateshead",
            "Stevenage",
            "High Wycombe",
            "Oldham",
            "Dudley",
            "Wigan",
            "Poole",
            "Exeter",
            "Cheltenham",
            "Lincoln",
            "Chester",
            "Barnsley",
            "Bath",
            "Chatham",
            "Wakefield",
            "Barrow-in-Furness",
            "Clydebank",
            "Paisley",
            "Kilmarnock",
            "Livingston",
            "Hamilton",
            "Ayr",
            "Perth",
            "Inverness",
            "Stirling",
            "Dumfries"
            // Add more cities
        ]
    },
    AU: {
        country: 10,
        language: 'en',
        countryMentions: ['AU', 'Australia'],
        regions: [
            "New South Wales", "NSW", "Central Coast", "Hunter Region", "Illawarra", "Mid North Coast", "Northern Rivers", "Orana", "Riverina", "South Coast", "Southern Highlands", "New England",
            "Victoria", "VIC", "Barwon South West", "Gippsland", "Grampians", "Hume", "Loddon Mallee",
            "Queensland", "QLD", "Darling Downs", "Central Queensland", "Far North Queensland", "North Queensland", "South East Queensland", "Wide Bay–Burnett",
            "South Australia", "SA", "Adelaide Plains", "Barossa", "Eyre Peninsula", "Far North", "Fleurieu Peninsula", "Kangaroo Island", "Limestone Coast", "Murray Mallee", "Riverland", "Yorke Peninsula",
            "Western Australia", "WA", "Gascoyne", "Goldfields-Esperance", "Great Southern", "Kimberley", "Mid West", "Peel", "Perth", "Pilbara", "South West", "Wheatbelt",
            "Tasmania", "TAS", "Central Highlands", "East Coast", "Midlands", "North West", "South East", "Southern", "Western",
            "Northern Territory", "NT", "Alice Springs", "Barkly Tableland", "Daly", "Darwin", "East Arnhem", "Katherine", "Victoria River",
            "Australian Capital Territory", "ACT", "Canberra"
            // Add more regions
        ],
        cities: [
            "Sydney",
            "Melbourne",
            "Brisbane",
            "Perth",
            "Adelaide",
            "Gold Coast",
            "Canberra",
            "Newcastle",
            "Wollongong",
            "Logan City",
            "Geelong",
            "Hobart",
            "Townsville",
            "Cairns",
            "Toowoomba",
            "Darwin",
            "Ballarat",
            "Bendigo",
            "Launceston",
            "Mackay",
            "Rockhampton",
            "Bunbury",
            "Bundaberg",
            "Hervey Bay",
            "Wagga Wagga",
            "Coffs Harbour",
            "Gladstone",
            "Shepparton",
            "Maitland",
            "Tweed Heads",
            "Melton",
            "Mildura",
            "Warrnambool",
            "Nowra",
            "Bathurst",
            "Kalgoorlie",
            "Albany",
            "Mount Gambier",
            "Traralgon",
            "Geraldton",
            "Busselton",
            "Whyalla"
            // Add more cities
        ]
    },
    NZ : {
        country: 10,
        language: 'en',
        countryMentions: ['NZ', 'New Zealand'],
        regions: [
            'Auckland',
            'Wellington',
            'Christchurch'
            // Add more regions
        ],
        cities: [
            'Auckland',
            'Wellington',
            'Christchurch'
            // Add more cities
        ]
    },
    DE: {
        country: 10,
        language: 'de',
        countryMentions: ['GER', 'Germany', 'Deutschland', 'DE'],
        regions: [
            "Baden-Württemberg", "BW",
            "Bavaria", "Bayern", "BY",
            "Berlin", "BE",
            "Brandenburg", "BB",
            "Bremen", "HB",
            "Hamburg", "HH",
            "Hesse", "Hessen", "HE",
            "Lower Saxony", "Niedersachsen", "NI",
            "Mecklenburg-Vorpommern", "MV",
            "North Rhine-Westphalia", "Nordrhein-Westfalen", "NW",
            "Rhineland-Palatinate", "Rheinland-Pfalz", "RP",
            "Saarland", "SL",
            "Saxony", "Sachsen", "SN",
            "Saxony-Anhalt", "Sachsen-Anhalt", "ST",
            "Schleswig-Holstein", "SH",
            "Thuringia", "Thüringen", "TH"
            // Add more regions
        ],
        cities: [
            "Berlin",
            "Hamburg",
            "Munich", "München",
            "Cologne", "Köln",
            "Frankfurt",
            "Stuttgart",
            "Düsseldorf",
            "Dortmund",
            "Essen",
            "Leipzig",
            "Bremen",
            "Dresden",
            "Hanover", "Hannover",
            "Nuremberg", "Nürnberg",
            "Duisburg",
            "Bochum",
            "Wuppertal",
            "Bielefeld",
            "Bonn",
            "Münster",
            "Karlsruhe",
            "Mannheim",
            "Augsburg",
            "Wiesbaden",
            "Gelsenkirchen",
            "Mönchengladbach",
            "Braunschweig",
            "Chemnitz",
            "Kiel",
            "Aachen",
            "Halle",
            "Magdeburg",
            "Freiburg",
            "Krefeld",
            "Lübeck",
            "Oberhausen",
            "Erfurt",
            "Mainz",
            "Rostock",
            "Kassel",
            "Hagen",
            "Saarbrücken",
            "Hamm",
            "Potsdam",
            "Ludwigshafen",
            "Oldenburg",
            "Leverkusen",
            "Osnabrück",
            "Solingen",
            "Heidelberg",
            "Herne",
            "Neuss",
            "Darmstadt",
            "Paderborn",
            "Regensburg",
            "Ingolstadt",
            "Würzburg",
            "Wolfsburg",
            "Ulm",
            "Heilbronn",
            "Pforzheim",
            "Göttingen",
            "Bottrop",
            "Trier",
            "Recklinghausen",
            "Reutlingen",
            "Bremerhaven",
            "Koblenz",
            "Bergisch Gladbach",
            "Jena",
            "Remscheid",
            "Erlangen",
            "Moers",
            "Siegen",
            "Hildesheim",
            "Salzgitter"
            // Add more cities
        ]
    },
    AT: {
        country: 10,
        language: 'en',
        countryMentions: ['AST', 'Austria', 'Österreich'],
        regions: [
            "Burgenland", "BG",
            "Carinthia", "Kärnten", "KTN",
            "Lower Austria", "Niederösterreich", "NO",
            "Upper Austria", "Oberösterreich", "OO",
            "Salzburg", "S",
            "Styria", "Steiermark", "ST",
            "Tyrol", "Tirol", "T",
            "Vorarlberg", "V",
            "Vienna", "Wien", "W"
            // Add more regions
        ],
        cities: [
            "Vienna", "Wien",
            "Graz",
            "Linz",
            "Salzburg",
            "Innsbruck",
            "Klagenfurt",
            "Villach",
            "Wels",
            "St. Pölten",
            "Dornbirn",
            "Wiener Neustadt",
            "Steyr",
            "Feldkirch",
            "Bregenz",
            "Leonding",
            "Klosterneuburg",
            "Baden bei Wien",
            "Wolfsberg",
            "Leoben",
            "Krems an der Donau",
            "Traun",
            "Amstetten",
            "Lustenau",
            "Kapfenberg",
            "Hallein",
            "Mödling",
            "Braunau am Inn",
            "Spittal an der Drau",
            "Schwechat",
            "Saalfelden am Steinernen Meer",
            "Tulln an der Donau",
            "Hohenems",
            "Telfs",
            "Bludenz",
            "Ansfelden",
            "Stockerau",
            "Feldbach",
            "Hollabrunn",
            "Sankt Johann im Pongau"
            // Add more cities
        ]
    },
    FR: {
        country: 10,
        language: 'fr',
        countryMentions: ['FR', 'France', 'République française'],
        regions: [
            "Auvergne-Rhône-Alpes", "ARA",
            "Bourgogne-Franche-Comté", "BFC",
            "Brittany", "Bretagne",
            "Centre-Val de Loire", "CVL",
            "Corsica", "Corse",
            "Grand Est",
            "Hauts-de-France",
            "Île-de-France",
            "Normandy", "Normandie",
            "Nouvelle-Aquitaine",
            "Occitanie",
            "Pays de la Loire",
            "Provence-Alpes-Côte d'Azur", "PACA"
            // Add more regions
        ],
        cities:[
            "Paris",
            "Marseille",
            "Lyon",
            "Toulouse",
            "Nice",
            "Nantes",
            "Strasbourg",
            "Montpellier",
            "Bordeaux",
            "Lille",
            "Rennes",
            "Reims",
            "Le Havre",
            "Saint-Étienne",
            "Toulon",
            "Grenoble",
            "Dijon",
            "Angers",
            "Nîmes",
            "Villeurbanne",
            "Saint-Denis",
            "Le Mans",
            "Aix-en-Provence",
            "Clermont-Ferrand",
            "Brest",
            "Tours",
            "Limoges",
            "Amiens",
            "Perpignan",
            "Metz",
            "Besançon",
            "Orléans",
            "Mulhouse",
            "Rouen",
            "Caen",
            "Nancy",
            "Argenteuil",
            "Montreuil",
            "Saint-Paul",
            "Roubaix",
            "Tourcoing",
            "Fort-de-France",
            "Saint-Denis",
            "Avignon",
        ]
    },
    IT: {
        country: 10,
        language: 'it',
        countryMentions: ['IT', 'Italy', 'Italia', 'Repubblica Italiana'],
        regions: [
            "Abruzzo", "ABR",
            "Aosta Valley", "Valle d'Aosta", "VDA",
            "Apulia", "Puglia", "PUG",
            "Basilicata", "BAS",
            "Calabria", "CAL",
            "Campania", "CAM",
            "Emilia-Romagna", "EMR",
            "Friuli-Venezia Giulia", "FVG",
            "Lazio", "LAZ",
            "Liguria", "LIG",
            "Lombardy", "Lombardia", "LOM",
            "Marche", "MAR",
            "Molise", "MOL",
            "Piedmont", "Piemonte", "PIE",
            "Sardinia", "Sardegna", "SAR",
            "Sicily", "Sicilia", "SIC",
            "Tuscany", "Toscana", "TOS",
            "Trentino-South Tyrol", "Trentino-Alto Adige", "TAA",
            "Umbria", "UMB",
            "Veneto", "VEN"

        ],
        cities: [
            "Rome", "Roma",
            "Milan", "Milano",
            "Naples", "Napoli",
            "Turin", "Torino",
            "Palermo",
            "Genoa", "Genova",
            "Bologna",
            "Florence", "Firenze",
            "Bari",
            "Catania",
            "Venice", "Venezia",
            "Verona",
            "Messina",
            "Padua", "Padova",
            "Trieste",
            "Taranto",
            "Brescia",
            "Prato",
            "Parma",
            "Modena",
            "Reggio Calabria",
            "Reggio Emilia",
            "Perugia",
            "Livorno",
            "Ravenna",
            "Cagliari",
            "Foggia",
            "Rimini",
            "Salerno",
            "Ferrara",
            "Sassari",
            "Latina",
            "Giugliano in Campania",
            "Monza",
            "Siracusa",
            "Pescara",
            "Bergamo",
            "Forlì",
            "Trento",
            "Vicenza",
            "Terni",
            "Bolzano", "Bozen",
            "Novara",
            "Piacenza",
            "Ancona",
            "Andria",
            "Arezzo",
            "Udine",
            "Cesena",
            "Lecce",
            "Pesaro",
            "Barletta",
            "Alessandria",
            "La Spezia",
            "Pisa",
            "Catanzaro",
            "Pistoia",
            "Guidonia Montecelio",
            "Lucca",
            "Casoria",
            "Como",
            "Marsala",
            "Cosenza",
            "Gela",
            "Varese",
            "Cinisello Balsamo",
            "Asti",
            "Grosseto",
            "Caserta",
            "Pavia",
            "L'Aquila",
            "Cremona",
            "Massa",
            "Trapani",
            "Carpi",
            "Altamura",
            "Imola",
            "Lamezia Terme",
            "Ragusa",
            "Agrigento"
        ]
    },
    ES: {
        country: 10,
        language: 'es',
        countryMentions: ['ES', 'Spain', 'España', 'Reino de España'],
        regions: [
            "Andalusia", "Andalucía",
            "Aragon", "Aragón",
            "Asturias", "Principado de Asturias",
            "Balearic Islands", "Islas Baleares",
            "Basque Country", "País Vasco",
            "Canary Islands", "Islas Canarias",
            "Cantabria",
            "Castile and León", "Castilla y León",
            "Castile-La Mancha", "Castilla-La Mancha",
            "Catalonia", "Cataluña",
            "Extremadura",
            "Galicia",
            "La Rioja",
            "Madrid", "Comunidad de Madrid",
            "Murcia", "Región de Murcia",
            "Navarre", "Navarra",
            "Valencian Community", "Comunidad Valenciana"
        ],
        cities: [
            "Madrid",
            "Barcelona",
            "Valencia",
            "Seville", "Sevilla",
            "Zaragoza",
            "Málaga",
            "Murcia",
            "Palma",
            "Las Palmas de Gran Canaria",
            "Bilbao",
            "Alicante",
            "Córdoba",
            "Valladolid",
            "Vigo",
            "Gijón",
            "L'Hospitalet de Llobregat",
            "A Coruña",
            "Vitoria-Gasteiz",
            "Granada",
            "Elche",
            "Oviedo",
            "Santa Cruz de Tenerife",
            "Badalona",
            "Cartagena",
            "Terrassa",
            "Jerez de la Frontera",
            "Sabadell",
            "Móstoles",
            "Alcalá de Henares",
            "Pamplona",
            "Fuenlabrada",
            "Almería",
            "San Sebastián", "Donostia",
            "Leganés",
            "Burgos",
            "Santander",
            "Castellón de la Plana",
            "Getafe",
            "Albacete",
            "Alcorcón",
            "Logroño",
            "Badajoz",
            "Huelva",
            "Salamanca",
            "Marbella",
            "Lleida",
            "Tarragona",
            "León",
            "Cádiz",
            "Jaén",
            "Ourense",
            "Lugo",
            "Santiago de Compostela",
            "Gerona", "Girona",
            "Cáceres",
            "Melilla",
            "Ceuta"
        ]
    },
    DN: {
        country: 10,
        language: 'da',
        countryMentions: ['DN', 'Denmark', 'Danmark', 'Kingdom of Denmark', 'Kongeriget Danmark', 'Danish Realm', 'Danmarks Rige'],
        regions: [
            "Capital Region of Denmark", "Hovedstaden",
            "Central Denmark Region", "Midtjylland",
            "North Denmark Region", "Nordjylland",
            "Region Zealand", "Sjælland",
            "Region of Southern Denmark", "Syddanmark"
        ],
        cities: [
            "Copenhagen", "København",
            "Aarhus",
            "Odense",
            "Aalborg",
            "Esbjerg",
            "Randers",
            "Kolding",
            "Horsens",
            "Vejle",
            "Roskilde",
            "Herning",
            "Hørsholm",
            "Helsingør",
            "Silkeborg",
            "Næstved",
            "Fredericia",
            "Ballerup",
            "Viborg",
            "Køge",
            "Holstebro",
            "Taastrup",
            "Slagelse",
            "Hillerød",
            "Sønderborg",
            "Svendborg",
            "Hjørring",
            "Frederikshavn",
            "Nørresundby",
            "Ringsted",
            "Greve Strand",
            "Kalundborg",
            "Skive",
            "Birkerød",
            "Glostrup",
            "Holbæk",
            "Frederiksberg",
            "Rødovre",
            "Lyngby",
            "Farum",
            "Haderslev"
        ]
    },

    // Add more countries
};

let scores = {
    US: {
        score: 0,
        name: "United States"
    },
    UK: {
        score: 0,
        name: "United Kingdom"
    },
    AU: {
        score: 0,
        name: "Australia"
    },
    NZ: {
        score: 0,
        name: "New Zealand"
    },
    DE: {
        score: 0,
        name: "Germany"
    },
    AT: {
        score: 0,
        name: "Austria"
    
    },
    FR: {
        score: 0,
        name: "France"
    },
    IT: {
        score: 0,
        name: "Italy"
    },
    ES: {
        score: 0,
        name: "Spain"
    },
    DN: {
        score: 0,
        name: "Denmark"
    }
    // Add more countries
}

function getCountryByScore(locations, countryFromURL = null, language) {
    
    //TODO increase score by domain extension: .co.uk., .de, etc.
    
    console.log('received country: ', countryFromURL);
    if(countryFromURL){
        countryFromURL = convertCountryFromURLToCountryCode(countryFromURL);
        console.log('Country from URL: ', countryFromURL);
        scores[countryFromURL].score += 5;
    }
    
    for (const country in countryData) {
        
        const data = countryData[country];
        
        
        for(const lang of data.language){
            if(lang === language){
                scores[country].score += 4;
            }
        }
        
        // Check for region mentions
        for (const region of data.regions) {
            if (locations.includes(region)) {
                scores[country].score += 10;
            }
        }
        
        // Check for city mentions
        for (const city of data.cities) {
            if (locations.includes(city)) {
                scores[country].score += 10;
            }
        }
    }
    
    if (Object.values(scores).every(score => score === 0)) {
        return null;
    }
    
    let highestScoreCountry = Object.entries(scores).reduce((a, b) => a[1].score > b[1].score ? a : b)[1];
    console.log(scores);
    resetScores();
    return highestScoreCountry.score >= 5 ? highestScoreCountry : null;
}

function convertCountryFromURLToCountryCode(countryFromURL){
    switch(countryFromURL){
        case 'United States':
            return 'US';
        case 'United Kingdom':
            return 'UK';
        case 'Australia':
            return 'AU';
        case 'New Zealand':
            return 'NZ';
        case 'Germany':
            return 'DE';
        case 'Austria':
            return 'AT';
        case 'France':
            return 'FR';
        case 'Italy':
            return 'IT';
        case 'Spain':
            return 'ES';
        case 'Denmark':
            return 'DN';
        default:
            return null;
    }
}

function resetScores (){
    scores = {
        US: 0,
        UK: 0,
        AU: 0,
        NZ: 0,
        DE: 0,
        AT: 0,
        FR: 0,
        IT: 0,
        ES: 0,
        DN: 0
    }
}

module.exports = { getCountryByScore };