const postalCodeRegex = {
    Albania: /^\d{4}$/,
    Andorra: /^AD\d{3}$/,
    Armenia: /^(37)?\d{4}$/,
    Austria: /^\d{4}$/,
    Azerbaijan: /^(AZ)*(\d{4})$/,
    Belarus: /^\d{6}$/,
    Belgium: /^\d{4}$/,
    'Bosnia and Herzegovina': /^\d{5}$/,
    Bulgaria: /^\d{4}$/,
    Croatia: /^\d{5}$/,
    Cyprus: /^\d{4}$/,
    'Czech Republic': /^\d{3} \d{2}$/,
    Denmark: /^\d{4}$/,
    Estonia: /^\d{5}$/,
    Finland: /^\d{5}$/,
    France: /^\d{5}$/,
    Georgia: /^\d{4}$/,
    Germany: /^\d{5}$/,
    Greece: /^\d{5}$/,
    Hungary: /^\d{4}$/,
    Iceland: /^\d{3}$/,
    Ireland: /^(?!.*(?:O))[A-Z]\d{2}$/,
    Italy: /^\d{5}$/,
    Kazakhstan: /^\d{6}$/,
    Kosovo: /^\d{5}$/,
    Latvia: /^(LV-)?\d{4}$/,
    Liechtenstein: /^(FL-)?(948[5-9]|949[0-7])$/,
    Lithuania: /^\d{5}$/,
    Luxembourg: /^(L-)?\d{4}$/,
    Malta: /^[A-Z]{3} \d{4}$/,
    Moldova: /^\d{4}$/,
    Monaco: /^980\d{2}$/,
    Montenegro: /^\d{5}$/,
    Netherlands: /^\d{4} ?[A-Z]{2}$/,
    'North Macedonia': /^\d{4}$/,
    Norway: /^\d{4}$/,
    Poland: /^\d{2}-\d{3}$/,
    Portugal: /^\d{4}-\d{3}$/,
    Romania: /\b\d{5,6}\b/,
    Russia: /^\d{6}$/,
    'San Marino': /^(4789\d)$/,
    Serbia: /^\d{5}$/,
    Slovakia: /^\d{3} \d{2}$/,
    Slovenia: /^\d{4}$/,
    Spain: /^(?:0[1-9]|[1-4]\d|5[0-2])\d{3}$/,
    Sweden: /^\d{3} ?\d{2}$/,
    Switzerland: /^\d{4}$/,
    Turkey: /^\d{5}$/,
    Ukraine: /^\d{5}$/,
    'United Kingdom': /^([A-PR-UWYZa-pr-uwyz][A-HK-Ya-hk-y]?[0-9][0-9]?[ABEHMNPRVWXYa-behmnprvwxy]? ?[0-9][ABD-HJLN-UW-Zabd-hjln-uw-z]{2}|GIR ?0A{2})$/,
    'Vatican City': /^00120$/,
    'Antigua and Barbuda': /^(?:ANT)?[0-9]{4}$/,
    Bahamas: /^(?:BAH)?[0-9]{5}$/,
    Barbados: /^(?:BRB)?[0-9]{5}$/,
    Belize: /^(?:BLZ)?[0-9]{4}$/,
    Canada: /^[A-Za-z]\d[A-Za-z] \d[A-Za-z]\d$/,
    'Costa Rica': /^\d{4,5}$/,
    Cuba: /^\d{5}$/,
    Dominica: /^(?:DMA)?[0-9]{4}$/,
    'Dominican Republic': /^\d{5}$/,
    'El Salvador': /^\d{4}$/,
    Grenada: /^(?:GRD)?[0-9]{4}$/,
    Guatemala: /^\d{5}$/,
    Haiti: /^\d{4}$/,
    Honduras: /^\d{5}$/,
    Jamaica: /^(?:JAM)?[0-9]{2}$/,
    Mexico: /^\d{5}$/,
    Nicaragua: /^\d{7}$/,
    Panama: /^\d{6}$/,
    'Saint Kitts and Nevis': /^(?:KN)?[0-9]{4}$/,
    'Saint Lucia': /^(?:LCA)?[0-9]{4}$/,
    'Saint Vincent and the Grenadines': /^(?:VCT)?[0-9]{4}$/,
    'Trinidad and Tobago': /^(?:TTO)?[0-9]{6}$/,
    'United States': /^\d{5}(?:-\d{4})?$/,
    Argentina: /^\d{4}$/,
    Bolivia: /^\d{4}$/,
    Brazil: /^\d{5}-\d{3}$/,
    Chile: /^\d{7}$/,
    Colombia: /^\d{6}$/,
    Ecuador: /^\d{6}$/,
    Guyana: /^[a-zA-Z\d ]+$/,
    Paraguay: /^\d{4}$/,
    Peru: /^\d{5}$/,
    Suriname: /^[a-zA-Z\d ]+$/,
    Uruguay: /^\d{5}$/,
    Venezuela: /^\d{4}$/,
}

function getPostalCodeFormat(country) {
    return postalCodeRegex[country];
}

module.exports = getPostalCodeFormat;